// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright 2026 The `OpenHTTPA` Foundation (openhttpa.org)

//! Mock quote verifier — accepts quotes generated by [`openhttpa_tee::mock`].

use openhttpa_proto::{AttestQuote, QuoteType};
use openhttpa_tee::mock::verify_mock_quote;

use crate::verifier::{EatClaims, QuoteVerifier, VerificationError, VerificationResult};

/// Verifies mock quotes produced by `MockTeeProvider`.
///
/// Supports simulation of multiple TEE types (TDX, SNP, TPM, GPU) for
/// autonomous CI/CD verification.
#[derive(Default)]
pub struct MockVerifier {
    result: Option<VerificationResult>,
}

impl MockVerifier {
    /// Create a new `MockVerifier` with a pre-configured result.
    #[must_use]
    pub const fn new(result: VerificationResult) -> Self {
        Self {
            result: Some(result),
        }
    }
}

impl QuoteVerifier for MockVerifier {
    fn verify<'a>(
        &'a self,
        quote: &'a AttestQuote,
        report_data: &'a [u8; 64],
    ) -> std::pin::Pin<
        Box<
            dyn std::future::Future<Output = Result<VerificationResult, VerificationError>>
                + Send
                + 'a,
        >,
    > {
        Box::pin(async move {
            // 1. Verify the mock hash binding
            verify_mock_quote(quote, report_data)
                .map_err(|_e| VerificationError::SignatureInvalid)?;

            // 2. Return pre-configured result if available
            if let Some(ref res) = self.result {
                return Ok(res.clone());
            }

            // 3. Generate a structured result based on the quote type
            let (model, version, tee_class) = match quote.quote_type {
                QuoteType::Tdx => ("Intel TDX", "v1.0", openhttpa_proto::TeeClass::IntelTdx),
                QuoteType::SevSnp => ("AMD SEV-SNP", "v2.0", openhttpa_proto::TeeClass::AmdSevSnp),
                QuoteType::Tpm => ("TPM 2.0", "v1.0", openhttpa_proto::TeeClass::Tpm),
                QuoteType::NvidiaGpu => {
                    ("NVIDIA H100", "v1.0", openhttpa_proto::TeeClass::NvidiaGpu)
                }
                _ => ("Mock TEE", "v0.0", openhttpa_proto::TeeClass::Mock),
            };

            Ok(VerificationResult {
                claims: EatClaims {
                    hwmodel: Some(model.to_owned()),
                    hwversion: Some(version.to_owned()),
                    dbgstat: Some(1), // Mock is always considered debug-mode
                    boot_progress: Some("mock-measurement".to_owned()),
                    security_version: Some(1),
                    tee_class: Some(tee_class),
                    iat: Some(
                        std::time::SystemTime::now()
                            .duration_since(std::time::UNIX_EPOCH)
                            .unwrap_or_default()
                            .as_secs(),
                    ),
                    ..Default::default()
                },
                tcb_status: "UpToDate".to_owned(),
                measurement: Some("mock-measurement".to_owned()),
                signer_id: Some("mock-signer".to_owned()),
                ..Default::default()
            })
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use openhttpa_tee::{QuoteRequest, mock::MockTeeProvider, provider::TeeProvider};

    #[tokio::test]
    async fn mock_verifier_round_trip() {
        let provider = MockTeeProvider::default();
        let rd = [0x55u8; 64];
        let quote = provider
            .generate_quote(&QuoteRequest { report_data: rd })
            .unwrap();
        let verifier = MockVerifier::default();
        let result = verifier.verify(&quote, &rd).await.unwrap();
        assert!(result.claims.hwmodel.is_some());
    }

    #[tokio::test]
    async fn mock_verifier_composite_round_trip() {
        let provider = MockTeeProvider::default();
        let rd = [0xaa; 64];

        let q1 = provider
            .generate_quote(&QuoteRequest { report_data: rd })
            .unwrap();
        let q2 = provider
            .generate_quote(&QuoteRequest { report_data: rd })
            .unwrap();

        let verifier = MockVerifier::default();
        let bundle_res = verifier.verify_bundle(&[q1, q2], &rd).await.unwrap();

        assert_eq!(bundle_res.secondary.len(), 1);
    }
}
