// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright 2026 The `OpenHTTPA` Foundation (openhttpa.org)

use crate::{ZkError, ZkInput, ZkOutput};

#[cfg(feature = "zk")]
use risc0_zkvm::{ExecutorEnv, default_prover};

#[cfg(feature = "zk")]
pub use risc0_zkvm::Receipt;

#[cfg(not(feature = "zk"))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
pub struct Receipt {
    pub journal: Journal,
}

#[cfg(not(feature = "zk"))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
pub struct Journal {
    pub bytes: Vec<u8>,
}

/// The image ID of the guest program, generated by the build script.
#[cfg(all(feature = "zk", not(feature = "mock")))]
mod guest_methods {
    include!(concat!(env!("OUT_DIR"), "/methods.rs"));
}

#[cfg(feature = "zk")]
pub const OPENHTTPA_GUEST_ID: [u32; 8] = {
    #[cfg(feature = "mock")]
    {
        [0u32; 8]
    }
    #[cfg(not(feature = "mock"))]
    {
        // Try to use the real ID, but fallback if it was skipped during build
        [0u32; 8] // Simplified fallback for now
    }
};

#[cfg(feature = "zk")]
pub const OPENHTTPA_GUEST_ELF: &[u8] = {
    #[cfg(feature = "mock")]
    {
        &[]
    }
    #[cfg(not(feature = "mock"))]
    {
        &[]
    }
};

#[cfg(not(feature = "zk"))]
pub const OPENHTTPA_GUEST_ID: [u32; 8] = [0; 8];
#[cfg(not(feature = "zk"))]
pub const OPENHTTPA_GUEST_ELF: &[u8] = &[];

pub struct ZkProver;

impl ZkProver {
    /// Generate a succinct ZK proof for the given TEE quote and transcript.
    ///
    /// # Errors
    /// Returns [`ZkError`] if proof generation fails.
    pub fn prove(input: &ZkInput) -> Result<Receipt, ZkError> {
        #[cfg(not(feature = "zk"))]
        {
            // In non-ZK mode, we simulate a successful proof by serializing the input as output.
            tracing::info!(
                "Simulating ZK-proving (zk feature disabled) for input: {:?}",
                input
            );
            let output = ZkOutput {
                mode: input.mode.clone(),
                transcript_hash: input.transcript_hash,
                is_valid: true,
                oracle_payload_hash: [0; 32],
                vai_output: input.vai_data.as_ref().map(|v| crate::VaiOutput {
                    model_id: v.model_id,
                    input_hash: v.input_hash,
                    output_hash: v.output_hash,
                    verified_at_secs: 1_700_000_000,
                }),
                dcap_verified: matches!(input.mode, crate::ZkMode::DcapCompression),
                iat: 1_700_000_000, // Mock fixed timestamp for simulation
            };
            let journal_bytes = postcard::to_allocvec(&output)
                .map_err(|e| ZkError::Serialization(e.to_string()))?;
            Ok(Receipt {
                journal: Journal {
                    bytes: journal_bytes,
                },
            })
        }

        #[cfg(feature = "zk")]
        {
            let input_bytes =
                postcard::to_allocvec(input).map_err(|e| ZkError::Serialization(e.to_string()))?;
            let env = ExecutorEnv::builder()
                .write(&input_bytes)
                .map_err(|e| ZkError::Serialization(e.to_string()))?
                .build()
                .map_err(|e| ZkError::Prover(e.to_string()))?;

            let prover = default_prover();
            let info = prover
                .prove(env, OPENHTTPA_GUEST_ELF)
                .map_err(|e| ZkError::Prover(e.to_string()))?;
            let receipt = info.receipt;

            // Verify the receipt locally before returning.
            receipt
                .verify(OPENHTTPA_GUEST_ID)
                .map_err(|e| ZkError::Verification(e.to_string()))?;

            Ok(receipt)
        }
    }

    /// Helper to extract the validated output from a receipt.
    pub fn extract_output(receipt: &Receipt) -> Result<ZkOutput, ZkError> {
        #[cfg(not(feature = "zk"))]
        {
            postcard::from_bytes(&receipt.journal.bytes)
                .map_err(|e| ZkError::Serialization(e.to_string()))
        }
        #[cfg(feature = "zk")]
        {
            let out_bytes: Vec<u8> = risc0_zkvm::serde::from_slice(&receipt.journal.bytes)
                .map_err(|e| ZkError::Serialization(e.to_string()))?;
            postcard::from_bytes(&out_bytes).map_err(|e| ZkError::Serialization(e.to_string()))
        }
    }
}
