// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright 2026 The `OpenHTTPA` Foundation (openhttpa.org)

use crate::{ZkError, ZkInput, ZkOutput};

#[cfg(feature = "zk")]
use risc0_zkvm::{ExecutorEnv, default_prover};

#[cfg(feature = "zk")]
pub use risc0_zkvm::Receipt;

#[cfg(not(feature = "zk"))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
pub struct Receipt {
    pub journal: Journal,
}

#[cfg(not(feature = "zk"))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
pub struct Journal {
    pub bytes: Vec<u8>,
}

/// The image ID and ELF constants for the guest program.
///
/// Three compile-time paths:
///
/// 1. `openhttpa_zk_stub` (set by build.rs when ZK build is skipped) →
///    includes the checked-in stub with sentinel zero/empty values so that
///    static-analysis tools (CodeQL, rust-analyzer, Clippy) can resolve all
///    call sites without a full RISC Zero build.
///
/// 2. Normal ZK build (feature = "zk", not feature = "mock", stub not set) →
///    includes the file generated by `risc0_build::embed_methods()` into
///    `$OUT_DIR/methods.rs` at compile time.
///
/// 3. Mock ZK build (feature = "mock") → constants are all-zero / empty (no
///    OUT_DIR file is needed; the prover short-circuits before using them).
#[cfg(all(feature = "zk", not(feature = "mock")))]
mod guest_methods {
    #[cfg(openhttpa_zk_stub)]
    include!("stubs/methods.rs");

    #[cfg(not(openhttpa_zk_stub))]
    include!(concat!(env!("OUT_DIR"), "/methods.rs"));
}

// ─── Guest image constants ────────────────────────────────────────────────────
//
// SEC-02: Using all-zero GUEST_ID is equivalent to disabling proof verification
// entirely — any guest image would pass `receipt.verify(OPENHTTPA_GUEST_ID)`.
//
// Resolution per compile path:
//
//  • `feature = "mock"` or `not(feature = "zk")` → sentinel zeros are acceptable
//    because the prover short-circuits before `verify()` is reached.
//
//  • Real ZK build (feature = "zk", not mock, not stub) → must use the image
//    ID embedded by `risc0_build::embed_methods()` in `build.rs`.  The
//    `openhttpa_zk_stub` cfg flag is set by `build.rs` when the RISC Zero
//    guest build is skipped (CI fast paths, rust-analyzer, etc.).  In that
//    case a compile-time error is emitted to prevent accidental shipping of
//    stub constants in a "production" binary.

/// Image ID of the OpenHTTPA ZK guest program.
///
/// Used by [`ZkVerifier`] to authenticate that a receipt was produced by the
/// genuine OpenHTTPA circuit.  **Must not be all-zeros in production builds.**
#[cfg(all(feature = "zk", not(feature = "mock")))]
pub const OPENHTTPA_GUEST_ID: [u32; 8] = {
    #[cfg(openhttpa_zk_stub)]
    {
        // Build stub: constants are placeholders only.  The compile error below
        // fires if someone tries to call `ZkProver::prove()` with real proving
        // while the stub is active.
        //
        // NOTE: we cannot use `compile_error!` here as a `const` initialiser,
        // so the guard is instead enforced inside `ZkProver::prove()`.
        [0u32; 8]
    }
    #[cfg(not(openhttpa_zk_stub))]
    {
        guest_methods::OPENHTTPA_ZK_GUEST_ID
    }
};

/// ELF binary of the OpenHTTPA ZK guest program.
#[cfg(all(feature = "zk", not(feature = "mock")))]
pub const OPENHTTPA_GUEST_ELF: &[u8] = {
    #[cfg(openhttpa_zk_stub)]
    {
        &[]
    }
    #[cfg(not(openhttpa_zk_stub))]
    {
        guest_methods::OPENHTTPA_ZK_GUEST_ELF
    }
};

// Mock path: sentinels are safe because the prover never calls verify().
#[cfg(all(feature = "zk", feature = "mock"))]
pub const OPENHTTPA_GUEST_ID: [u32; 8] = [0u32; 8];
#[cfg(all(feature = "zk", feature = "mock"))]
pub const OPENHTTPA_GUEST_ELF: &[u8] = &[];

// Non-ZK path: sentinels are safe because ZkProver::prove() uses the stub path.
#[cfg(not(feature = "zk"))]
pub const OPENHTTPA_GUEST_ID: [u32; 8] = [0; 8];
#[cfg(not(feature = "zk"))]
pub const OPENHTTPA_GUEST_ELF: &[u8] = &[];

pub struct ZkProver;

impl ZkProver {
    /// Generate a succinct ZK proof for the given TEE quote and transcript.
    ///
    /// # Errors
    /// Returns [`ZkError`] if proof generation fails.
    pub fn prove(input: &ZkInput) -> Result<Receipt, ZkError> {
        #[cfg(not(feature = "zk"))]
        {
            // In non-ZK mode, we simulate a successful proof by serializing the input as output.
            tracing::info!(
                "Simulating ZK-proving (zk feature disabled) for input: {:?}",
                input
            );
            let output = ZkOutput {
                mode: input.mode.clone(),
                transcript_hash: input.transcript_hash,
                is_valid: true,
                oracle_payload_hash: [0; 32],
                vai_output: input.vai_data.as_ref().map(|v| crate::VaiOutput {
                    model_id: v.model_id,
                    input_hash: v.input_hash,
                    output_hash: v.output_hash,
                    verified_at_secs: 1_700_000_000,
                }),
                dcap_verified: matches!(input.mode, crate::ZkMode::DcapCompression),
                iat: 1_700_000_000, // Mock fixed timestamp for simulation
            };
            let journal_bytes = postcard::to_allocvec(&output)
                .map_err(|e| ZkError::Serialization(e.to_string()))?;
            Ok(Receipt {
                journal: Journal {
                    bytes: journal_bytes,
                },
            })
        }

        #[cfg(feature = "zk")]
        {
            // SEC-02 guard: If the stub build flag is set the guest ELF is empty
            // and the image ID is all-zeros.  Attempting to prove with an empty
            // ELF would panic; attempting to verify against [0u32;8] would accept
            // ANY proof.  Fail explicitly instead.
            #[cfg(openhttpa_zk_stub)]
            {
                return Err(ZkError::Prover(
                    "ZK guest program was not compiled into this binary (build \
                     stub is active).  Recompile with a full RISC Zero guest \
                     build to enable real proving."
                        .to_owned(),
                ));
            }

            #[cfg(not(openhttpa_zk_stub))]
            {
                // Belt-and-suspenders runtime check: if the image ID is still
                // all-zeros despite the build flag being absent, something is
                // very wrong in the build system.  Refuse to continue.
                if OPENHTTPA_GUEST_ID == [0u32; 8] {
                    return Err(ZkError::Prover(
                        "OPENHTTPA_GUEST_ID is all-zeros — ZK guest image was \
                         not correctly embedded.  This is a build configuration \
                         error; do not suppress this check."
                            .to_owned(),
                    ));
                }

                let input_bytes = postcard::to_allocvec(input)
                    .map_err(|e| ZkError::Serialization(e.to_string()))?;
                let env = ExecutorEnv::builder()
                    .write(&input_bytes)
                    .map_err(|e| ZkError::Serialization(e.to_string()))?
                    .build()
                    .map_err(|e| ZkError::Prover(e.to_string()))?;

                let prover = default_prover();
                let info = prover
                    .prove(env, OPENHTTPA_GUEST_ELF)
                    .map_err(|e| ZkError::Prover(e.to_string()))?;
                let receipt = info.receipt;

                // Verify the receipt locally before returning.
                receipt
                    .verify(OPENHTTPA_GUEST_ID)
                    .map_err(|e| ZkError::Verification(e.to_string()))?;

                Ok(receipt)
            }
        }
    }

    /// Helper to extract the validated output from a receipt.
    pub fn extract_output(receipt: &Receipt) -> Result<ZkOutput, ZkError> {
        #[cfg(not(feature = "zk"))]
        {
            postcard::from_bytes(&receipt.journal.bytes)
                .map_err(|e| ZkError::Serialization(e.to_string()))
        }
        #[cfg(feature = "zk")]
        {
            let out_bytes: Vec<u8> = risc0_zkvm::serde::from_slice(&receipt.journal.bytes)
                .map_err(|e| ZkError::Serialization(e.to_string()))?;
            postcard::from_bytes(&out_bytes).map_err(|e| ZkError::Serialization(e.to_string()))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{DcapCollateral, VaiInput, ZkInput, ZkMode};

    fn make_oracle_input() -> ZkInput {
        ZkInput {
            mode: ZkMode::Oracle,
            transcript_hash: [0x42u8; 48],
            quote_bytes: vec![0x01, 0x02, 0x03],
            report_data: [0u8; 64],
            oracle_data: Some(b"oracle payload".to_vec()),
            vai_data: None,
            dcap_collateral: None,
        }
    }

    fn make_dcap_input() -> ZkInput {
        ZkInput {
            mode: ZkMode::DcapCompression,
            transcript_hash: [0x11u8; 48],
            quote_bytes: vec![0xde, 0xad, 0xbe, 0xef],
            report_data: [0u8; 64],
            oracle_data: None,
            vai_data: None,
            dcap_collateral: Some(DcapCollateral {
                pck_cert: vec![0xca],
                intermediate_ca: vec![0xfe],
                root_ca: vec![0x00],
                tcb_info: vec![0x01],
                qe_identity: vec![0x02],
            }),
        }
    }

    fn make_vai_input() -> ZkInput {
        ZkInput {
            mode: ZkMode::VerifiedAi,
            transcript_hash: [0x33u8; 48],
            quote_bytes: vec![],
            report_data: [0u8; 64],
            oracle_data: None,
            vai_data: Some(VaiInput {
                model_id: [0x01u8; 32],
                input_hash: [0x02u8; 32],
                output_hash: [0x03u8; 32],
            }),
            dcap_collateral: None,
        }
    }

    #[test]
    fn prove_oracle_mode_returns_receipt() {
        let input = make_oracle_input();
        let receipt = ZkProver::prove(&input).expect("prove should succeed");
        assert!(!receipt.journal.bytes.is_empty());
    }

    #[test]
    fn prove_dcap_mode_returns_receipt() {
        let input = make_dcap_input();
        let receipt = ZkProver::prove(&input).expect("prove should succeed");
        assert!(!receipt.journal.bytes.is_empty());
    }

    #[test]
    fn prove_vai_mode_returns_receipt_with_vai_output() {
        let input = make_vai_input();
        let receipt = ZkProver::prove(&input).expect("prove should succeed");
        let output = ZkProver::extract_output(&receipt).expect("extract should succeed");
        assert!(output.vai_output.is_some());
        let vai = output.vai_output.unwrap();
        assert_eq!(vai.model_id, [0x01u8; 32]);
    }

    #[test]
    fn extract_output_round_trips_transcript_hash() {
        let input = make_oracle_input();
        let receipt = ZkProver::prove(&input).unwrap();
        let output = ZkProver::extract_output(&receipt).unwrap();
        assert_eq!(output.transcript_hash, [0x42u8; 48]);
        assert!(output.is_valid);
    }

    #[test]
    fn extract_output_dcap_sets_dcap_verified() {
        let input = make_dcap_input();
        let receipt = ZkProver::prove(&input).unwrap();
        let output = ZkProver::extract_output(&receipt).unwrap();
        assert!(output.dcap_verified);
    }

    #[cfg(not(feature = "zk"))]
    #[test]
    fn receipt_journal_is_postcard_encoded_output() {
        let input = make_oracle_input();
        let receipt = ZkProver::prove(&input).unwrap();
        // The journal bytes should be valid postcard-encoded ZkOutput
        let decoded: ZkOutput = postcard::from_bytes(&receipt.journal.bytes)
            .expect("journal should deserialize as ZkOutput");
        assert!(decoded.is_valid);
    }
}
