# SPDX-License-Identifier: Apache-2.0 OR MIT
# Copyright 2026 The OpenHTTPA Foundation (openhttpa.org)

packages:
  - '.'
  - 'bindings/nodejs'
  - 'tests/web'
  - 'demo/multiparty-webapp/frontend/wasm'
