/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Send a secure agent-to-agent message.
 *
 * # Errors
 *
 * Returns an error if the connection or message transmission fails.
 */
export declare function a2ASendMessage(agentId: string, targetUrl: string, messageType: string, payload: any): Promise<void>

/**
 * Create a new `OpenHTTPA` attested session.
 *
 * Returns the `AtB` ID as a hyphenated UUID string.
 *
 * # Errors
 *
 * Returns an error if the URI is invalid or the attestation handshake fails.
 */
export declare function attestHandshake(serverUri: string): Promise<string>

/**
 * Perform a confidential LLM chat request.
 *
 * `messages` is an array of `[role, content]` pairs.  Elements that are
 * not exactly two strings are skipped.
 * Returns the assistant's reply.
 *
 * # Errors
 *
 * Returns an error if the URI is invalid, the handshake fails, or the
 * inference request fails.
 */
export declare function confidentialChat(serverUri: string, model: string, messages: Array<Array<string>>): Promise<string>

/**
 * Perform a confidential MCP call.
 *
 * # Errors
 *
 * Returns an error if the handshake or the MCP request fails.
 */
export declare function mcpCall(serverUri: string, method: string, params?: any | undefined | null): Promise<any>
