// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright 2026 The `OpenHTTPA` Foundation (openhttpa.org)

// # ZK Guest Methods Stub
//
// This file is a compile-time stub for the RISC Zero guest image ID and ELF
// constants that are normally generated by [`risc0_build::embed_methods`] into
// `$OUT_DIR/methods.rs` at build time.
//
// ## When this file is used
//
// It is included instead of the `OUT_DIR`-generated file when the build
// script detects that the RISC Zero guest build has been skipped (i.e., when
// `OPENHTTPA_SKIP_ZK_BUILD=1` or `RISC0_SKIP_BUILD=1` is set).  The build
// script emits `cargo:rustc-cfg=openhttpa_zk_stub` to signal this condition.
//
// ## Purpose
//
// Providing this stub allows static-analysis tools (CodeQL, rust-analyzer,
// Clippy) to fully type-check and resolve all call sites in `prover.rs`
// without requiring a full RISC Zero guest build.  Without a stub the
// `include!(concat!(env!("OUT_DIR"), "/methods.rs"))` macro would expand to
// nothing (or fail), leaving call targets unresolved and suppressing CodeQL
// quality metrics.
//
// ## Contract with `risc0_build::embed_methods`
//
// The real generated file defines `OPENHTTPA_ZK_GUEST_ID: [u32; 8]` and
// `OPENHTTPA_ZK_GUEST_ELF: &[u8]`.  This stub provides identical symbols
// with zero-value / empty-slice sentinel values that are recognisably invalid
// at runtime (so any accidental use in production is immediately detectable).

/// Stub image ID — all-zero sentinel; always invalid in production.
///
/// The real value is a RISC Zero image ID computed from the guest ELF hash.
/// Using all-zeros here makes any accidental runtime use of the stub
/// immediately detectable (the verifier will reject it).
pub const OPENHTTPA_ZK_GUEST_ID: [u32; 8] = [0u32; 8];

/// Stub guest ELF — empty slice sentinel; always invalid in production.
///
/// The real value is the compiled RISC Zero guest binary embedded as a byte
/// slice.  An empty slice will cause the prover to fail immediately if this
/// stub is ever used at runtime, making misuse self-evident.
pub const OPENHTTPA_ZK_GUEST_ELF: &[u8] = &[];
