// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright 2026 The `OpenHTTPA` Foundation (AIQL.org)

//! Structured attestation evidence and bundles for `OpenHTTPA`.
//!
//! This module provides type-safe representations of evidence from different TEE
//! vendors. By using structured evidence instead of raw byte blobs, we allow
//! the verification layer to perform more granular checks (e.g. verifying
//! specific PCR values or GPU runtime immutable measurements).

use bytes::Bytes;
use openhttpa_proto::{AttestQuote, QuoteType};
use serde::{Deserialize, Serialize};

/// Detailed attestation evidence for Intel TDX (Trust Domain Extensions).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TdxEvidence {
    /// The TDX Quote generated by the Intel Quoting Enclave.
    pub quote: Bytes,
    /// URI pointing to the Intel PCK (Provisioning Certification Key) chain.
    pub pck_cert_uri: Option<String>,
}

/// Detailed attestation evidence for AMD SEV-SNP (Secure Nested Paging).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SevSnpEvidence {
    /// The SNP Attestation Report signed by the AMD PSP (Platform Security Processor).
    pub report: Bytes,
    /// URI pointing to the AMD VCEK (Versioned Chip Endorsement Key) chain.
    pub vcek_cert_uri: Option<String>,
}

/// Detailed attestation evidence for TPM 2.0 (Trusted Platform Module).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TpmEvidence {
    /// The TPM PCR Quote signed by an AIK (Attestation Identity Key).
    pub quote: Bytes,
    /// A map of PCR indices to their measured digest values.
    pub pcr_values: std::collections::HashMap<u32, Vec<u8>>,
    /// URI pointing to the AIK certificate or endorsement chain.
    pub aik_cert_uri: Option<String>,
}

/// Detailed attestation evidence for NVIDIA Hopper GPUs (H100/H200).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NvidiaGpuEvidence {
    /// The Runtime Immutable Measurement (RIM) report from the GPU.
    pub rim_report: Bytes,
    /// URI pointing to the NVIDIA GPU device certificate chain.
    pub gpu_cert_uri: Option<String>,
}

/// Detailed attestation evidence for AWS Nitro Enclaves.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AwsNitroEvidence {
    /// The CBOR-encoded NSM attestation document.
    pub document: Bytes,
}

/// A structured container for all supported types of TEE hardware evidence.
///
/// This enum is `#[non_exhaustive]` to allow for future hardware support
/// (e.g. RISC-V Keystone) without breaking existing match patterns.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AttestationEvidence {
    /// Evidence from an Intel TDX Trust Domain.
    Tdx(TdxEvidence),
    /// Evidence from an AMD SEV-SNP Confidential VM.
    SevSnp(SevSnpEvidence),
    /// Evidence from a TPM 2.0 module.
    Tpm(TpmEvidence),
    /// Evidence from a confidential NVIDIA GPU.
    NvidiaGpu(NvidiaGpuEvidence),
    /// Evidence from an AWS Nitro Enclave.
    AwsNitro(AwsNitroEvidence),
    /// Mock evidence for testing and autonomous verification.
    Mock(Bytes),
}

impl AttestationEvidence {
    /// Transform structured evidence into a wire-format [`AttestQuote`].
    ///
    /// This method is used when preparing the `OpenHTTPA` `Attestation` header
    /// for transmission over the network. It binds the evidence to a specific
    /// `qudd` (Quote User Defined Data) to ensure freshness.
    #[must_use]
    pub fn to_quote(&self, qudd: Bytes) -> AttestQuote {
        match self {
            Self::Tdx(e) => AttestQuote {
                quote_type: QuoteType::Tdx,
                raw: e.quote.clone(),
                qudd,
                collateral_uris: e.pck_cert_uri.clone().into_iter().collect(),
            },
            Self::SevSnp(e) => AttestQuote {
                quote_type: QuoteType::SevSnp,
                raw: e.report.clone(),
                qudd,
                collateral_uris: e.vcek_cert_uri.clone().into_iter().collect(),
            },
            Self::Tpm(e) => AttestQuote {
                quote_type: QuoteType::Tpm,
                raw: e.quote.clone(),
                qudd,
                collateral_uris: e.aik_cert_uri.clone().into_iter().collect(),
            },
            Self::NvidiaGpu(e) => AttestQuote {
                quote_type: QuoteType::NvidiaGpu,
                raw: e.rim_report.clone(),
                qudd,
                collateral_uris: e.gpu_cert_uri.clone().into_iter().collect(),
            },
            Self::AwsNitro(e) => AttestQuote {
                quote_type: QuoteType::AwsNitro,
                raw: e.document.clone(),
                qudd,
                collateral_uris: vec![], // PKI certs are generally embedded in the CBOR doc
            },
            Self::Mock(raw) => AttestQuote {
                quote_type: QuoteType::Mock,
                raw: raw.clone(),
                qudd,
                collateral_uris: vec![],
            },
        }
    }
}

/// A bundle of attestation evidence produced by one or more TEE hardware units.
///
/// In modern secure systems, a single node may have multiple TEEs (e.g. a
/// CPU TEE for logic and a GPU TEE for AI processing). The `EvidenceBundle`
/// groups these into a single verifiable unit.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvidenceBundle {
    /// The primary attestation (usually the host CPU TEE).
    pub primary: AttestationEvidence,
    /// Additional secondary attestations (e.g. peripheral TEEs, TPMs).
    pub secondary: Vec<AttestationEvidence>,
}

impl EvidenceBundle {
    /// Flatten the evidence bundle into a list of wire-format [`AttestQuote`]s.
    ///
    /// Useful for generating the final protocol headers where all quotes
    /// must share the same session-specific `qudd`.
    #[must_use]
    pub fn to_quotes(&self, qudd: &Bytes) -> Vec<AttestQuote> {
        let mut quotes = vec![self.primary.to_quote(qudd.clone())];
        for s in &self.secondary {
            quotes.push(s.to_quote(qudd.clone()));
        }
        quotes
    }
}
