// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright 2026 The `OpenHTTPA` Foundation (openhttpa.org)

//! Structured attestation evidence and bundles for `OpenHTTPA`.
//!
//! This module provides type-safe representations of evidence from different TEE
//! vendors. By using structured evidence instead of raw byte blobs, we allow
//! the verification layer to perform more granular checks (e.g. verifying
//! specific PCR values or GPU runtime immutable measurements).

use bytes::Bytes;
use openhttpa_proto::{AttestQuote, QuoteType};
use serde::{Deserialize, Serialize};

/// Detailed attestation evidence for Intel TDX (Trust Domain Extensions).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TdxEvidence {
    /// The TDX Quote generated by the Intel Quoting Enclave.
    pub quote: Bytes,
    /// URI pointing to the Intel PCK (Provisioning Certification Key) chain.
    pub pck_cert_uri: Option<String>,
}

/// Detailed attestation evidence for AMD SEV-SNP (Secure Nested Paging).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SevSnpEvidence {
    /// The SNP Attestation Report signed by the AMD PSP (Platform Security Processor).
    pub report: Bytes,
    /// URI pointing to the AMD VCEK (Versioned Chip Endorsement Key) chain.
    pub vcek_cert_uri: Option<String>,
}

/// Detailed attestation evidence for TPM 2.0 (Trusted Platform Module).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TpmEvidence {
    /// The TPM PCR Quote signed by an AIK (Attestation Identity Key).
    pub quote: Bytes,
    /// A map of PCR indices to their measured digest values.
    pub pcr_values: std::collections::HashMap<u32, Vec<u8>>,
    /// URI pointing to the AIK certificate or endorsement chain.
    pub aik_cert_uri: Option<String>,
}

/// Detailed attestation evidence for NVIDIA Hopper GPUs (H100/H200).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NvidiaGpuEvidence {
    /// The Runtime Immutable Measurement (RIM) report from the GPU.
    pub rim_report: Bytes,
    /// URI pointing to the NVIDIA GPU device certificate chain.
    pub gpu_cert_uri: Option<String>,
}

/// Detailed attestation evidence for AWS Nitro Enclaves.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AwsNitroEvidence {
    /// The CBOR-encoded NSM attestation document.
    pub document: Bytes,
}

/// A structured container for all supported types of TEE hardware evidence.
///
/// This enum is `#[non_exhaustive]` to allow for future hardware support
/// (e.g. RISC-V Keystone) without breaking existing match patterns.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
pub enum AttestationEvidence {
    /// Evidence from an Intel TDX Trust Domain.
    Tdx(TdxEvidence),
    /// Evidence from an AMD SEV-SNP Confidential VM.
    SevSnp(SevSnpEvidence),
    /// Evidence from a TPM 2.0 module.
    Tpm(TpmEvidence),
    /// Evidence from a confidential NVIDIA GPU.
    NvidiaGpu(NvidiaGpuEvidence),
    /// Evidence from an AWS Nitro Enclave.
    AwsNitro(AwsNitroEvidence),
    /// Mock evidence for testing and autonomous verification.
    Mock(Bytes),
}

impl AttestationEvidence {
    /// Transform structured evidence into a wire-format [`AttestQuote`].
    ///
    /// This method is used when preparing the `OpenHTTPA` `Attestation` header
    /// for transmission over the network. It binds the evidence to a specific
    /// `qudd` (Quote User Defined Data) to ensure freshness.
    #[must_use]
    pub fn to_quote(&self, qudd: Bytes) -> AttestQuote {
        match self {
            Self::Tdx(e) => AttestQuote {
                quote_type: QuoteType::Tdx,
                format: openhttpa_proto::QuoteFormat::default(),
                raw: e.quote.clone(),
                qudd,
                collateral_uris: e.pck_cert_uri.clone().into_iter().collect(),
            },
            Self::SevSnp(e) => AttestQuote {
                quote_type: QuoteType::SevSnp,
                format: openhttpa_proto::QuoteFormat::default(),
                raw: e.report.clone(),
                qudd,
                collateral_uris: e.vcek_cert_uri.clone().into_iter().collect(),
            },
            Self::Tpm(e) => AttestQuote {
                quote_type: QuoteType::Tpm,
                format: openhttpa_proto::QuoteFormat::default(),
                raw: e.quote.clone(),
                qudd,
                collateral_uris: e.aik_cert_uri.clone().into_iter().collect(),
            },
            Self::NvidiaGpu(e) => AttestQuote {
                quote_type: QuoteType::NvidiaGpu,
                format: openhttpa_proto::QuoteFormat::default(),
                raw: e.rim_report.clone(),
                qudd,
                collateral_uris: e.gpu_cert_uri.clone().into_iter().collect(),
            },
            Self::AwsNitro(e) => AttestQuote {
                quote_type: QuoteType::AwsNitro,
                format: openhttpa_proto::QuoteFormat::default(),
                raw: e.document.clone(),
                qudd,
                collateral_uris: vec![], // PKI certs are generally embedded in the CBOR doc
            },
            Self::Mock(raw) => AttestQuote {
                quote_type: QuoteType::Mock,
                format: openhttpa_proto::QuoteFormat::default(),
                raw: raw.clone(),
                qudd,
                collateral_uris: vec![],
            },
        }
    }

    /// Normalise vendor-specific evidence into vendor-neutral [`EatClaims`](openhttpa_proto::EatClaims).
    ///
    /// This is the M4 Multi-Vendor Federation bridge: it maps each vendor's
    /// evidence fields to the common `EatClaims` struct, filling in
    /// `tee_class`, `hwmodel`, and `oemid` so that [`FederatedVerifier`] and
    /// downstream policy engines can operate without vendor-specific logic.
    ///
    /// Fields that require live verification (e.g. measurement, SVN) are left
    /// as `None`; the verifier layer fills them in after validating the quote.
    ///
    /// [`FederatedVerifier`]: (openhttpa_attestation::federation::FederatedVerifier)
    #[must_use]
    pub fn to_eat_claims(&self) -> openhttpa_proto::EatClaims {
        use openhttpa_proto::{EatClaims, TeeClass};
        match self {
            Self::Tdx(_) => EatClaims {
                tee_class: Some(TeeClass::IntelTdx),
                hwmodel: Some("Intel TDX".to_owned()),
                oemid: Some("Intel".to_owned()),
                ..Default::default()
            },
            Self::SevSnp(_) => EatClaims {
                tee_class: Some(TeeClass::AmdSevSnp),
                hwmodel: Some("AMD SEV-SNP".to_owned()),
                oemid: Some("AMD".to_owned()),
                ..Default::default()
            },
            Self::Tpm(_) => EatClaims {
                tee_class: Some(TeeClass::Tpm),
                hwmodel: Some("TPM 2.0".to_owned()),
                oemid: None,
                ..Default::default()
            },
            Self::NvidiaGpu(_) => EatClaims {
                tee_class: Some(TeeClass::NvidiaGpu),
                hwmodel: Some("NVIDIA Hopper GPU".to_owned()),
                oemid: Some("NVIDIA".to_owned()),
                ..Default::default()
            },
            Self::AwsNitro(_) => EatClaims {
                tee_class: Some(TeeClass::AwsNitro),
                hwmodel: Some("AWS Nitro Enclave".to_owned()),
                oemid: Some("Amazon".to_owned()),
                ..Default::default()
            },
            Self::Mock(_) => EatClaims {
                tee_class: Some(TeeClass::Mock),
                hwmodel: Some("Mock TEE".to_owned()),
                oemid: None,
                ..Default::default()
            },
        }
    }
}

/// A bundle of attestation evidence produced by one or more TEE hardware units.
///
/// In modern secure systems, a single node may have multiple TEEs (e.g. a
/// CPU TEE for logic and a GPU TEE for AI processing). The `EvidenceBundle`
/// groups these into a single verifiable unit.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvidenceBundle {
    /// The primary attestation (usually the host CPU TEE).
    pub primary: AttestationEvidence,
    /// Additional secondary attestations (e.g. peripheral TEEs, TPMs).
    pub secondary: Vec<AttestationEvidence>,
}

impl EvidenceBundle {
    /// Flatten the evidence bundle into a list of wire-format [`AttestQuote`]s.
    ///
    /// Useful for generating the final protocol headers where all quotes
    /// must share the same session-specific `qudd`.
    #[must_use]
    pub fn to_quotes(&self, qudd: &Bytes) -> Vec<AttestQuote> {
        let mut quotes = vec![self.primary.to_quote(qudd.clone())];
        for s in &self.secondary {
            quotes.push(s.to_quote(qudd.clone()));
        }
        quotes
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use openhttpa_proto::TeeClass;

    #[test]
    fn test_evidence_to_quote() {
        let qudd = Bytes::from_static(b"qudd");

        let tdx = AttestationEvidence::Tdx(TdxEvidence {
            quote: Bytes::from_static(b"tdx"),
            pck_cert_uri: None,
        });
        let q = tdx.to_quote(qudd.clone());
        assert_eq!(q.quote_type, QuoteType::Tdx);
        assert_eq!(q.raw.as_ref(), b"tdx");

        let mock = AttestationEvidence::Mock(Bytes::from_static(b"mock"));
        let q = mock.to_quote(qudd.clone());
        assert_eq!(q.quote_type, QuoteType::Mock);

        let bundle = EvidenceBundle {
            primary: tdx,
            secondary: vec![mock],
        };
        let quotes = bundle.to_quotes(&qudd);
        assert_eq!(quotes.len(), 2);
    }

    #[test]
    fn test_evidence_to_eat_claims() {
        let mock = AttestationEvidence::Mock(Bytes::from_static(b"mock"));
        let claims = mock.to_eat_claims();
        assert_eq!(claims.tee_class, Some(TeeClass::Mock));
        assert_eq!(claims.hwmodel.unwrap(), "Mock TEE");
        assert!(claims.oemid.is_none());

        let snp = AttestationEvidence::SevSnp(SevSnpEvidence {
            report: Bytes::new(),
            vcek_cert_uri: None,
        });
        let claims = snp.to_eat_claims();
        assert_eq!(claims.tee_class, Some(TeeClass::AmdSevSnp));
        assert_eq!(claims.oemid.unwrap(), "AMD");
    }
}
