// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright 2026 The `OpenHTTPA` Foundation (openhttpa.org)

//! [`TeeProvider`] trait and associated types for hardware attestation.
//!
//! This module defines the core abstractions for Trusted Execution Environments (TEEs)
//! in `OpenHTTPA`. It supports a wide range of hardware (Intel TDX/SGX, AMD SEV-SNP,
//! Arm `TrustZone`, TPM 2.0) and allows for composite attestation where multiple
//! hardware units (e.g. CPU + GPU) provide a joint proof of integrity.

use std::sync::Arc;

use openhttpa_proto::{AttestQuote, QuoteType};
use thiserror::Error;

use crate::evidence::AttestationEvidence;

/// A request to generate a TEE attestation quote.
///
/// Contains the cryptographic binding (nonce) that ensures the freshness
/// and session-specific nature of the generated attestation.
#[derive(Debug, Clone)]
pub struct QuoteRequest {
    /// 64-byte report data to embed in the quote.
    ///
    /// This is typically the SHA-384 hash of the ephemeral public key share
    /// or the current handshake transcript. By embedding this in the hardware
    /// quote, we prove that the attestation was generated by the specific
    /// identity participating in the handshake.
    pub report_data: [u8; 64],
}

/// Errors returned by a TEE provider during detection, initialization, or quote generation.
// MED-06: non_exhaustive prevents breaking changes when new variants are added.
#[non_exhaustive]
#[derive(Debug, Error)]
pub enum TeeProviderError {
    /// The required TEE SDK or library is not found on the system.
    #[error("TEE SDK not available: {0}")]
    NotAvailable(String),

    /// The hardware failed to produce a valid attestation quote.
    #[error("quote generation failed: {0}")]
    QuoteGeneration(String),

    /// The TEE hardware or driver was found but not properly initialized.
    #[error("TEE not initialised")]
    NotInitialised,

    /// An error occurred within the secure enclave or TCB.
    #[error("enclave error: {0}")]
    Enclave(String),

    /// A failure in the low-level hardware driver (e.g. /dev/tdx-guest).
    #[error("hardware driver error: {0}")]
    Driver(String),

    /// The platform configuration (e.g. BIOS settings) prevents TEE usage.
    #[error("platform configuration error: {0}")]
    Config(String),
}

/// A pluggable TEE attestation provider (Legacy/Wire Interface).
///
/// This trait provides backward compatibility for the simple, byte-oriented
/// attestation flow. New implementations should prioritize [`TeeAdapter`].
pub trait TeeProvider: Send + Sync {
    /// Return the [`QuoteType`] produced by this provider (e.g. Tdx, `SevSnp`).
    fn quote_type(&self) -> QuoteType;

    /// Generate a single attestation quote binding `request.report_data`.
    ///
    /// # Errors
    /// Returns [`TeeProviderError`] if hardware is unavailable or generation fails.
    fn generate_quote(&self, request: &QuoteRequest) -> Result<AttestQuote, TeeProviderError>;

    /// Generate multiple attestation quotes (for composite TEEs like CPU+GPU).
    /// Defaults to returning a single-element vector containing the result of `generate_quote`.
    ///
    /// # Errors
    /// Returns [`TeeProviderError`] if hardware is unavailable or generation fails.
    fn generate_quotes(
        &self,
        request: &QuoteRequest,
    ) -> Result<Vec<AttestQuote>, TeeProviderError> {
        self.generate_quote(request).map(|q| vec![q])
    }

    /// Return `true` if the TEE hardware is present and usable.
    fn is_available(&self) -> bool;
}

/// A modern adapter for TEE hardware that produces structured evidence.
///
/// Unlike `TeeProvider`, which returns a flat byte blob, `TeeAdapter` returns
/// [`AttestationEvidence`], which preserves the typed nature of the evidence
/// (e.g. PCR values for TPM, RIM reports for GPUs).
pub trait TeeAdapter: Send + Sync {
    /// Return the [`QuoteType`] produced by this adapter.
    fn quote_type(&self) -> QuoteType;

    /// Generate structured evidence binding `request.report_data`.
    ///
    /// # Errors
    /// Returns [`TeeProviderError`] if the underlying hardware fails.
    fn generate_evidence(
        &self,
        request: &QuoteRequest,
    ) -> Result<AttestationEvidence, TeeProviderError>;

    /// Return `true` if the TEE hardware is present and usable.
    fn is_available(&self) -> bool;

    /// Optional: Initialize the hardware/driver.
    /// Default implementation is a no-op.
    ///
    /// # Errors
    /// Returns [`TeeProviderError`] if initialization fails.
    fn initialize(&self) -> Result<(), TeeProviderError> {
        Ok(())
    }

    /// Optional: Cleanup resources.
    /// Default implementation is a no-op.
    ///
    /// # Errors
    /// Returns [`TeeProviderError`] if shutdown fails.
    fn shutdown(&self) -> Result<(), TeeProviderError> {
        Ok(())
    }
}

/// Configuration for TEE provider selection and fallback behavior.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct TeeConfig {
    /// Allow fallback to `MockTeeProvider` if no hardware is found.
    ///
    /// > [!WARNING]
    /// > This should be `false` in production environments to ensure
    /// > genuine hardware attestation.
    pub allow_mock: bool,

    /// Preferred TEE type (e.g., "sgx", "tdx", "`sev_snp`").
    /// Overridden by `OPENHTTPA_TEE_PROVIDER` environment variable.
    pub preferred_type: Option<String>,
}

impl Default for TeeConfig {
    /// Default configuration: allows mock in debug builds, forbids it in release.
    fn default() -> Self {
        Self {
            allow_mock: cfg!(any(debug_assertions, feature = "mock")),
            preferred_type: None,
        }
    }
}

/// Automatically selects the best available TEE provider based on system capabilities.
///
/// Priority Order:
/// 1. NVIDIA GPU (if host TEE is present)
/// 2. Intel TDX
/// 3. AMD SEV-SNP
/// 4. Intel SGX
/// 5. TPM 2.0
/// 6. Arm `TrustZone`
///
/// # Errors
/// Returns [`TeeProviderError::NotAvailable`] if no TEE is found and mock is disabled.
pub fn detect_best_provider(config: &TeeConfig) -> Result<Arc<dyn TeeProvider>, TeeProviderError> {
    // 1. Check for environment variable override (highest priority)
    if let Ok(env_type) = std::env::var("OPENHTTPA_TEE_PROVIDER") {
        tracing::info!("Using TEE provider from OPENHTTPA_TEE_PROVIDER: {env_type}");
        return select_by_type(&env_type, config.allow_mock);
    }

    // 2. Check for preferred type in config
    if let Some(ref pref_type) = config.preferred_type {
        tracing::debug!("Attempting to use preferred TEE type: {pref_type}");
        return select_by_type(pref_type, config.allow_mock);
    }

    // 3. Priority-based detection

    #[cfg(feature = "nvidia_gpu")]
    {
        let p = crate::nvidia_gpu::NvidiaGpuTeeProvider;
        if TeeAdapter::is_available(&p) {
            tracing::info!("Detected NVIDIA GPU TEE");
            return Ok(Arc::new(p));
        }
    }

    #[cfg(feature = "tdx")]
    {
        let p = crate::tdx::TdxTeeProvider;
        if TeeAdapter::is_available(&p) {
            tracing::info!("Detected Intel TDX TEE");
            return Ok(Arc::new(p));
        }
    }

    #[cfg(feature = "sev_snp")]
    {
        let p = crate::sev_snp::SevSnpTeeProvider;
        if TeeAdapter::is_available(&p) {
            tracing::info!("Detected AMD SEV-SNP TEE");
            return Ok(Arc::new(p));
        }
    }

    #[cfg(feature = "aws_nitro")]
    {
        let p = crate::aws_nitro::AwsNitroTeeProvider;
        if TeeAdapter::is_available(&p) {
            tracing::info!("Detected AWS Nitro Enclaves TEE");
            return Ok(Arc::new(p));
        }
    }

    #[cfg(feature = "sgx")]
    {
        let p = crate::sgx::SgxTeeProvider;
        if TeeProvider::is_available(&p) {
            tracing::info!("Detected Intel SGX TEE");
            return Ok(Arc::new(p));
        }
    }

    #[cfg(feature = "tpm")]
    {
        let p = crate::tpm::TpmTeeAdapter;
        if TeeAdapter::is_available(&p) {
            tracing::info!("Detected TPM 2.0 TEE");
            return Ok(Arc::new(p));
        }
    }

    #[cfg(feature = "trustzone")]
    {
        let p = crate::trustzone::TrustZoneTeeProvider;
        if TeeProvider::is_available(&p) {
            tracing::info!("Detected Arm TrustZone TEE");
            return Ok(Arc::new(p));
        }
    }

    // 4. Fallback to Mock if allowed
    #[cfg(feature = "mock")]
    if config.allow_mock {
        // SA-07: Log at ERROR not WARN — mock attestation is not a routine fallback,
        // it is a security-relevant misconfiguration outside of CI/test environments.
        tracing::error!(
            security = true,
            "SECURITY: No hardware TEE detected; falling back to MockTeeProvider. \
             This is ONLY acceptable in test/CI environments. \
             Disable 'allow_mock' or enable a hardware TEE feature in production."
        );
        return Ok(Arc::new(crate::mock::MockTeeProvider::default()));
    }

    tracing::error!("No hardware TEE detected and Mock is disabled/unavailable");
    Err(TeeProviderError::NotAvailable(
        "No hardware TEE detected and Mock is disabled".to_owned(),
    ))
}

/// Helper to select a provider by its string name.
fn select_by_type(
    tee_type: &str,
    _allow_mock: bool,
) -> Result<Arc<dyn TeeProvider>, TeeProviderError> {
    match tee_type {
        "sgx" => {
            #[cfg(feature = "sgx")]
            return Ok(Arc::new(crate::sgx::SgxTeeProvider));
            #[cfg(not(feature = "sgx"))]
            return Err(TeeProviderError::NotAvailable(
                "SGX feature not enabled".to_owned(),
            ));
        }
        "tdx" => {
            #[cfg(feature = "tdx")]
            return Ok(Arc::new(crate::tdx::TdxTeeProvider));
            #[cfg(not(feature = "tdx"))]
            return Err(TeeProviderError::NotAvailable(
                "TDX feature not enabled".to_owned(),
            ));
        }
        "sev_snp" | "snp" => {
            #[cfg(feature = "sev_snp")]
            return Ok(Arc::new(crate::sev_snp::SevSnpTeeProvider));
            #[cfg(not(feature = "sev_snp"))]
            return Err(TeeProviderError::NotAvailable(
                "SEV-SNP feature not enabled".to_owned(),
            ));
        }
        "aws_nitro" | "nitro" => {
            #[cfg(feature = "aws_nitro")]
            return Ok(Arc::new(crate::aws_nitro::AwsNitroTeeProvider));
            #[cfg(not(feature = "aws_nitro"))]
            return Err(TeeProviderError::NotAvailable(
                "AWS Nitro feature not enabled".to_owned(),
            ));
        }
        "trustzone" => {
            #[cfg(feature = "trustzone")]
            return Ok(Arc::new(crate::trustzone::TrustZoneTeeProvider));
            #[cfg(not(feature = "trustzone"))]
            return Err(TeeProviderError::NotAvailable(
                "TrustZone feature not enabled".to_owned(),
            ));
        }
        "tpm" => {
            #[cfg(feature = "tpm")]
            return Ok(Arc::new(crate::tpm::TpmTeeAdapter));
            #[cfg(not(feature = "tpm"))]
            return Err(TeeProviderError::NotAvailable(
                "TPM feature not enabled".to_owned(),
            ));
        }
        "nvidia_gpu" | "nvidia" | "hopper" => {
            #[cfg(feature = "nvidia_gpu")]
            return Ok(Arc::new(crate::nvidia_gpu::NvidiaGpuTeeProvider));
            #[cfg(not(feature = "nvidia_gpu"))]
            return Err(TeeProviderError::NotAvailable(
                "NVIDIA GPU feature not enabled".to_owned(),
            ));
        }
        "mock" => {
            #[cfg(feature = "mock")]
            return Ok(Arc::new(crate::mock::MockTeeProvider::default()));
            #[cfg(not(feature = "mock"))]
            return Err(TeeProviderError::NotAvailable(
                "Mock feature not enabled".to_owned(),
            ));
        }
        _ => Err(TeeProviderError::Config(format!(
            "Unknown TEE provider type: {tee_type}"
        ))),
    }
}

/// A TEE provider that combines multiple underlying providers for composite attestation.
///
/// Useful for systems with multiple TEEs, such as a host TEE (TDX/SNP) and
/// a confidential GPU (NVIDIA Hopper). It ensures all TEEs contribute to the
/// joint proof of integrity.
pub struct CompositeTeeProvider {
    providers: Vec<std::sync::Arc<dyn TeeProvider>>,
}

impl CompositeTeeProvider {
    /// Create a new composite provider from a list of underlying providers.
    #[must_use]
    pub fn new(providers: Vec<std::sync::Arc<dyn TeeProvider>>) -> Self {
        Self { providers }
    }
}

/// Detects all available TEE providers and returns them grouped in a `CompositeTeeProvider`.
/// If no hardware providers are detected and `allow_mock` is true, it returns a mock provider.
///
/// # Errors
/// Returns [`TeeProviderError::NotAvailable`] if no hardware TEE is detected and Mock is disabled.
pub fn detect_all_providers(config: &TeeConfig) -> Result<CompositeTeeProvider, TeeProviderError> {
    let mut providers: Vec<Arc<dyn TeeProvider>> = Vec::new();

    #[cfg(feature = "nvidia_gpu")]
    {
        let p = crate::nvidia_gpu::NvidiaGpuTeeProvider;
        if TeeAdapter::is_available(&p) {
            providers.push(Arc::new(p));
        }
    }

    #[cfg(feature = "tdx")]
    {
        let p = crate::tdx::TdxTeeProvider;
        if TeeAdapter::is_available(&p) {
            providers.push(Arc::new(p));
        }
    }

    #[cfg(feature = "sev_snp")]
    {
        let p = crate::sev_snp::SevSnpTeeProvider;
        if TeeAdapter::is_available(&p) {
            providers.push(Arc::new(p));
        }
    }

    #[cfg(feature = "aws_nitro")]
    {
        let p = crate::aws_nitro::AwsNitroTeeProvider;
        if TeeAdapter::is_available(&p) {
            providers.push(Arc::new(p));
        }
    }

    #[cfg(feature = "sgx")]
    {
        let p = crate::sgx::SgxTeeProvider;
        if TeeProvider::is_available(&p) {
            providers.push(Arc::new(p));
        }
    }

    #[cfg(feature = "tpm")]
    {
        let p = crate::tpm::TpmTeeAdapter;
        if TeeAdapter::is_available(&p) {
            providers.push(Arc::new(p));
        }
    }

    #[cfg(feature = "trustzone")]
    {
        let p = crate::trustzone::TrustZoneTeeProvider;
        if TeeProvider::is_available(&p) {
            providers.push(Arc::new(p));
        }
    }

    if providers.is_empty() {
        #[cfg(feature = "mock")]
        if config.allow_mock {
            tracing::error!(
                security = true,
                "SECURITY: No hardware TEE detected; falling back to MockTeeProvider for federation. \
                 This is ONLY acceptable in test/CI environments."
            );
            providers.push(Arc::new(crate::mock::MockTeeProvider::default()));
        } else {
            return Err(TeeProviderError::NotAvailable(
                "No hardware TEE detected for federation and Mock is disabled".to_owned(),
            ));
        }
        #[cfg(not(feature = "mock"))]
        return Err(TeeProviderError::NotAvailable(
            "No hardware TEE detected for federation and Mock feature is not available".to_owned(),
        ));
    }

    Ok(CompositeTeeProvider::new(providers))
}

impl TeeProvider for CompositeTeeProvider {
    fn quote_type(&self) -> QuoteType {
        // Returns the first provider's type as a primary identity.
        self.providers.first().map_or_else(
            || QuoteType::Unknown("composite".to_owned()),
            |p| p.quote_type(),
        )
    }

    fn generate_quote(&self, request: &QuoteRequest) -> Result<AttestQuote, TeeProviderError> {
        // For single-quote requests, return the primary TEE's quote.
        self.providers
            .first()
            .ok_or_else(|| TeeProviderError::NotAvailable("no providers in composite".to_owned()))?
            .generate_quote(request)
    }

    fn generate_quotes(
        &self,
        request: &QuoteRequest,
    ) -> Result<Vec<AttestQuote>, TeeProviderError> {
        let mut quotes = Vec::new();
        for p in &self.providers {
            quotes.push(p.generate_quote(request)?);
        }
        Ok(quotes)
    }

    fn is_available(&self) -> bool {
        self.providers.iter().any(|p| p.is_available())
    }
}

/// A TEE provider that wraps another provider and compresses its quotes into ZK-SNARKs.
///
/// This enables high-assurance "ZAA" (ZK-Aggregated Attestation), where a multi-KB
/// hardware quote is reduced to a concise SNARK receipt.
#[cfg(feature = "zaa")]
pub struct ZkCompressedTeeProvider {
    inner: Arc<dyn TeeProvider>,
}

#[cfg(feature = "zaa")]
impl ZkCompressedTeeProvider {
    /// Create a new ZK-compressed provider wrapping `inner`.
    #[must_use]
    pub fn new(inner: Arc<dyn TeeProvider>) -> Self {
        Self { inner }
    }
}

#[cfg(feature = "zaa")]
impl TeeProvider for ZkCompressedTeeProvider {
    fn quote_type(&self) -> QuoteType {
        QuoteType::ZkCompressed
    }

    fn generate_quote(&self, request: &QuoteRequest) -> Result<AttestQuote, TeeProviderError> {
        // 1. Generate raw quote from the inner hardware provider
        let raw_quote = self.inner.generate_quote(request)?;

        // 2. Perform ZK-compression (ZAA)
        // Note: In a production system, we would fetch collateral (PCK, TCB Info) here.
        // For this milestone, we use a placeholder for collateral.
        let input = openhttpa_zk::ZkInput {
            mode: openhttpa_zk::ZkMode::DcapCompression,
            transcript_hash: request.report_data[..48].try_into().unwrap(),
            quote_bytes: raw_quote.raw.to_vec(),
            report_data: request.report_data,
            oracle_data: None,
            vai_data: None,
            dcap_collateral: Some(openhttpa_zk::DcapCollateral {
                pck_cert: vec![0x30; 128], // Mock PCK
                intermediate_ca: vec![0x30; 128],
                root_ca: vec![0x30; 128],
                tcb_info: b"{}".to_vec(),
                qe_identity: b"{}".to_vec(),
            }),
        };

        let receipt = openhttpa_zk::prover::ZkProver::prove(&input)
            .map_err(|e| TeeProviderError::Enclave(format!("ZK-proving failed: {e}")))?;

        // 3. Wrap receipt into a ZkCompressed AttestQuote
        let receipt_bytes = bincode::serialize(&receipt)
            .map_err(|e| TeeProviderError::Enclave(format!("Serialization failed: {e}")))?;

        Ok(AttestQuote {
            quote_type: QuoteType::ZkCompressed,
            raw: bytes::Bytes::from(receipt_bytes),
            qudd: bytes::Bytes::from(request.report_data.to_vec()),
            collateral_uris: raw_quote.collateral_uris,
        })
    }

    fn is_available(&self) -> bool {
        self.inner.is_available()
    }
}
