// SPDX-License-Identifier: Apache-2.0 OR MIT
// crates/openhttpa-attestation/examples/federated_mock_mesh.rs

use openhttpa_attestation::{
    MockVerifier,
    federation::{FederatedVerifier, ManifestTrustRoot},
};
use openhttpa_proto::{
    FederationEntry, FederationManifest, ManifestSignature, QuoteType, TeeClass,
};
use openhttpa_tee::{
    mock::MockTeeProvider,
    provider::{QuoteRequest, TeeProvider},
};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // SAFETY: single-threaded startup before any other threads are spawned.
    unsafe { std::env::set_var("OPENHTTPA_ALLOW_MOCK_HARDWARE", "1") };

    println!("=== M4 Autonomous Federation Demo ===\n");

    // 1. Configure the Federated Verifier with Quorum Trust Root
    let validator_a_key = vec![0xAA; 32];
    let validator_b_key = vec![0xBB; 32];
    let validator_c_key = vec![0xCC; 32];

    let trust_root = ManifestTrustRoot::Quorum {
        threshold: 2,
        validators: vec![
            validator_a_key.clone(),
            validator_b_key.clone(),
            validator_c_key.clone(),
        ],
    };

    let mut verifier = FederatedVerifier::new().with_trust_root(trust_root);

    // Register mock vendor verifiers for TDX and SNP
    verifier.add_vendor_verifier(TeeClass::IntelTdx, Box::new(MockVerifier::default()));
    verifier.add_vendor_verifier(TeeClass::AmdSevSnp, Box::new(MockVerifier::default()));

    // 2. Create and "sign" the Federation Manifest
    // In production, this would be generated by a config tool and signed offline
    // or signed by a quorum of mesh nodes via consensus.
    let manifest = FederationManifest {
        version: 1,
        issued_at: 0,
        expires_at: u64::MAX,
        entries: vec![
            FederationEntry {
                tee_class: TeeClass::IntelTdx,
                measurement_hex: String::new(), // wildcard for demo
                label: "mock-tdx-nodes".into(),
                min_svn: None,
                allow_debug: true,
            },
            FederationEntry {
                tee_class: TeeClass::AmdSevSnp,
                measurement_hex: String::new(), // wildcard for demo
                label: "mock-snp-nodes".into(),
                min_svn: None,
                allow_debug: true,
            },
        ],
        signature: ManifestSignature::Quorum {
            threshold: 2,
            signatures: vec![
                (validator_a_key, vec![1, 2, 3]), // mock signature from A
                (validator_b_key, vec![4, 5, 6]), // mock signature from B
            ],
        },
    };

    // Load the manifest into the verifier (validates the quorum signatures)
    println!("Loading federation manifest with 2-of-3 quorum signatures...");
    verifier.set_manifest(manifest).await?;
    println!("✅ Manifest loaded and signatures validated.\n");

    // 3. Generate Mock Quotes for TDX and SNP
    let report_data = [0x42u8; 64];

    println!("Generating mock Intel TDX quote...");
    let tdx_provider = MockTeeProvider::with_override(QuoteType::Tdx);
    let tdx_quote = tdx_provider.generate_quote(&QuoteRequest { report_data })?;

    println!("Generating mock AMD SEV-SNP quote...");
    let snp_provider = MockTeeProvider::with_override(QuoteType::SevSnp);
    let snp_quote = snp_provider.generate_quote(&QuoteRequest { report_data })?;

    // 4. Verify cross-vendor quotes
    println!("\n--- Cross-Vendor Verification ---");

    use openhttpa_attestation::verifier::QuoteVerifier;

    println!("Intel TDX node verifying AMD SEV-SNP quote...");
    let snp_result = verifier.verify(&snp_quote, &report_data).await?;
    println!("✅ SNP quote successfully verified and accepted by federation policy.");
    println!(
        "   Resolved TEE Class: {:?}",
        snp_result.claims.tee_class.unwrap()
    );

    println!("\nAMD SEV-SNP node verifying Intel TDX quote...");
    let tdx_result = verifier.verify(&tdx_quote, &report_data).await?;
    println!("✅ TDX quote successfully verified and accepted by federation policy.");
    println!(
        "   Resolved TEE Class: {:?}",
        tdx_result.claims.tee_class.unwrap()
    );

    println!("\n=== M4 Autonomous Federation Demo Complete ===");
    Ok(())
}
